services:
  backend:
    image: danish1922/knowledgetrace-backend:latest
    env_file: .env
    ports:
      - "8000:8000"
  frontend:
    image: danish1922/knowledgetrace-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
